name: Java CI

on:
  push:
    branches:
    - master
    - dev
    tags:
      - "v*.*"
  pull_request:
    branches:
    - master
    
jobs:
  create_release:
    name: "创建发布"
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: 下载构建
      uses: actions/download-artifact@v3.0.2
        
    - name: 创建发布
      uses: softprops/action-gh-release@v1
      
      with:
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        prerelease: true
        fail_on_unmatched_files: true
        name: AlchimiaVitae v0.0.3版本
        files: |
          artifacts/*
  build:
    if: startsWith(github.event.head_commit.message, '[CI skip]') == false
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.3.0
    - name: Set up JDK 17
      uses: actions/setup-java@v3.9.0
      with:
        java-version: 17
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn package --file pom.xml

    - name: 上传 The Bruh
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: |
           target/*.jar
